# Generated by Django 4.2 on 2023-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="audio",
            fields=[
                (
                    "audio_name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("audio_file", models.FileField(upload_to="audio_files")),
            ],
        ),
    ]
